"""add user_id to tags and contact_tags junction table

Revision ID: 0e5b34f239b3
Revises: b1c2d3e4f5a6
Create Date: 2026-06-06 14:06:29.665008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e5b34f239b3'
down_revision: Union[str, Sequence[str], None] = 'b1c2d3e4f5a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_tags',
    sa.Column('contact_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('contact_id', 'tag_id')
    )
    op.drop_index(op.f('ix_activities_contact_id'), table_name='activities')
    op.drop_constraint(op.f('activities_contact_id_fkey'), 'activities', type_='foreignkey')
    op.create_foreign_key(None, 'activities', 'contacts', ['contact_id'], ['id'])
    op.drop_index(op.f('ix_campaign_recipients_campaign_id'), table_name='campaign_recipients')
    op.drop_index(op.f('ix_campaign_recipients_contact_id'), table_name='campaign_recipients')
    op.add_column('tags', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'tags', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tags', type_='foreignkey')
    op.drop_column('tags', 'user_id')
    op.create_index(op.f('ix_campaign_recipients_contact_id'), 'campaign_recipients', ['contact_id'], unique=False)
    op.create_index(op.f('ix_campaign_recipients_campaign_id'), 'campaign_recipients', ['campaign_id'], unique=False)
    op.drop_constraint(None, 'activities', type_='foreignkey')
    op.create_foreign_key(op.f('activities_contact_id_fkey'), 'activities', 'contacts', ['contact_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_activities_contact_id'), 'activities', ['contact_id'], unique=False)
    op.drop_table('contact_tags')
    # ### end Alembic commands ###
